# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecommend.proto\x12\trecommend\"R\n\x10RecommnedRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x10\n\x08listsize\x18\x03 \x01(\x05\x12\r\n\x05token\x18\x04 \x01(\t\"G\n\x15RecommendResponseList\x12.\n\x08response\x18\x01 \x03(\x0b\x32\x1c.recommend.RecommendResponse\"\x99\x01\n\x11RecommendResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tnick_name\x18\x02 \x01(\t\x12\x0b\n\x03sex\x18\x03 \x01(\x05\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x05 \x01(\t\x12\x0c\n\x04like\x18\x06 \x01(\x08\x12\x11\n\timage_url\x18\x07 \x01(\t\x12\x12\n\nlast_login\x18\x08 \x01(\t2[\n\x0bRecommender\x12L\n\tRecommned\x12\x1b.recommend.RecommnedRequest\x1a .recommend.RecommendResponseList\"\x00\x42&Z$ryo29wx/caolila_interfaces/recommendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommend_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$ryo29wx/caolila_interfaces/recommend'
  _globals['_RECOMMNEDREQUEST']._serialized_start=30
  _globals['_RECOMMNEDREQUEST']._serialized_end=112
  _globals['_RECOMMENDRESPONSELIST']._serialized_start=114
  _globals['_RECOMMENDRESPONSELIST']._serialized_end=185
  _globals['_RECOMMENDRESPONSE']._serialized_start=188
  _globals['_RECOMMENDRESPONSE']._serialized_end=341
  _globals['_RECOMMENDER']._serialized_start=343
  _globals['_RECOMMENDER']._serialized_end=434
# @@protoc_insertion_point(module_scope)
